name: Pull Request Build

on:
  pull_request:
    branches:
      - dev
      - staging
      - production
    paths:
      - "**/*"

jobs:
  build:
    runs-on: windows-latest

    env:
      NODE_ENV: ${{ github.event.pull_request.base.ref }}
      APP_ENV: ${{ github.event.pull_request.base.ref }}
      JAVA_TOOL_OPTIONS: "-Dhttps.protocols=TLSv1.2,TLSv1.3"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Install Node.js (LTS 18.x)
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          npm install # or yarn install, depending on your project

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          ndk-version: 25.1.8937393
          cmake-version: 3.22.1
          build-tools: 33.0.2

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: C:\Users\RunnerUser\.gradle
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper

      - name: Clean Gradle
        run: |
          cd android
          ./gradlew clean

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease --info --stacktrace --debug

      - name: Check Java Version
        run: |
          java -version
