name: Build APK

on:
  push:
    branches:
      - main # Adjust to your target branch
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      APP_ENV: development # Set your default environment; can be overridden per job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node.js version required by your project

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "APP_ENV=${{ env.APP_ENV }}" >> $GITHUB_ENV

      - name: Run assembleRelease
        run: |
          cd android
          ./gradlew assembleRelease
        env:
          APP_ENV: ${{ env.APP_ENV }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
