name: Pull Request Build

on:
  pull_request:
    branches:
      - dev
      - staging
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ${{ github.event.pull_request.base.ref }}
      APP_ENV: ${{ github.event.pull_request.base.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Debug Java Environment
        run: |
          java -version
          echo $JAVA_HOME
          java -XshowSettings:properties -version

      - name: Update Certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper

      - name: Set Java TLS Protocols
        run: |
          echo "JAVA_TOOL_OPTIONS='-Dhttps.protocols=TLSv1.2,TLSv1.3'" >> $GITHUB_ENV

      - name: Test Network Connectivity
        run: |
          curl -I https://services.gradle.org

      - name: Grant execute permissions to gradlew
        run: chmod +x ./android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease
        env:
          APP_ENV: ${{ github.event.pull_request.base.ref }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-${{ github.event.pull_request.base.ref }}.apk
          path: android/app/build/outputs/apk/release/app-release.apk
